name: Example pynt yml 
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "API Security tests"

env:
  PYNT_CREDENTIALS: ${{ secrets.YOURPYNTID }}

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli 
    - name: get restful booker collection 
      run: | 
        curl https://raw.githubusercontent.com/cozyloon/Pynt-CI-CD/main/pynt-cicd.json -o pynt-cicd.json 
    - name: run pynt with newman integration 
      run: | 
        pynt newman --collection pynt-cicd.json --reporters
